name: Cactus
favicon: null
layout_spectrum: 0.37126207491382957
typography_spectrum: 0.11297892453148961
title: The Agency Growth Experts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#57aa6f'
    - '#000000'
    - '#00ff00'
    - '#008080'
    - '#808080'
  brandStrength: 0.5
  lightness: 0.47065122658386827
  saturation: 0.5
  rhythmicContrast: 0.5893078334629536
purpose: []
